# This workflows will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Make package
        run: make

      - name: Tar package
        run: tar -cvzf bk-hcm.tar.gz .

      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: bk-hcm.tar.gz

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ./bk-hcm

          # If true, an artifact with a matching name will be deleted before a new one is uploaded.
          # If false, the action will fail if an artifact for the given name already exists.
          # Does not fail if the artifact does not exist.
          # Optional. Default is 'false'
          overwrite: true
